[package]
name = "rmodbus-example-server"
version = "0.1.0"
authors = ["Sergei S. <div@altertech.com>"]
edition = "2018"

[dependencies]
rmodbus = { path = "../..", features=["std"] }
fixedvec = "0.2.4"

serial = "0.4.0"
