[package]
name = "rmodbus-example-app"
version = "0.1.0"
authors = ["Sergei S. <div@altertech.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rmodbus = { path = "../.." }
spin = "0.5.2"
