[package]
name = "rmodbus"
version = "0.1.0"
authors = ["Sergei S. <div@altertech.com>"]
edition = "2018"

[dependencies]
lazy_static = "1.4.0"
ieee754 = "0.2.6"

[dev-dependencies]
rand = "0.7.3"

#!test-threads = 1
